class Product {
  String producto,
      despliegue,
      descripcion,
      precioLista,
      activo,
      identificador,
      tipoProducto,
      fechaCreacion,
      productoPrecio,
      usuarioCreacion,
      activoDescripcion,
      fechaModificacion,
      usuarioModificacion,
      tipoProductoDescripcion;
  Product(
      this.producto,
      this.despliegue,
      this.descripcion,
      this.precioLista,
      this.activo,
      this.identificador,
      this.tipoProducto,
      this.fechaCreacion,
      this.productoPrecio,
      this.usuarioCreacion,
      this.activoDescripcion,
      this.fechaModificacion,
      this.usuarioModificacion,
      this.tipoProductoDescripcion);
  Product.fromJson(Map<String, dynamic> json)
      : producto = json["producto"].toString(),
        despliegue = json["despliegue"].toString(),
        descripcion = json["descripcion"].toString(),
        precioLista = json["precio_lista"].toString(),
        activo = json["activo"].toString(),
        identificador = json["identificador"].toString(),
        tipoProducto = json["tipo_producto"].toString(),
        fechaCreacion = json["fecha_creacion"].toString(),
        productoPrecio = json["producto_precio"].toString(),
        usuarioCreacion = json["usuario_creacion"].toString(),
        activoDescripcion = json["activo_descripcion"].toString(),
        fechaModificacion = json["fecha_modificacion"].toString(),
        usuarioModificacion = json["usuario_modificacion"].toString(),
        tipoProductoDescripcion = json["tipo_producto_descripcion"].toString();
}
